try {
  a;
} catch (e) {
  console.log("Err", +e);
}

// 연습문제
try {
  a;
} catch (e) {
  console.log("a");
}
